version: "3.4"

services:
  backend:
    image: node
    ports:
      - 100:3000  # Maps port 3000 inside the container to port 100 on the host
    volumes:
      - back_data:/app
    networks:
      - connect

  frontend:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - front_data:/app
    networks:
      - connect
    ports:
      - 101:80  # Maps port 80 inside the container to port 101 on the host

networks:
  connect:
    driver: bridge
    
volumes:
  back_data:
    driver: local
  front_data:
    driver: local