# Day 6: Set Up Persistent Storage for Docker Containers
# Objective: Configure persistent storage for data retention between container restarts.

version: 3.4

services:
  app:
    image: node
    ports:
      - 100:3000
    volumes:
      - app_data:/app
volumes:
  app_data:
    driver: local