version: "3.4"

services:
  app:
    image: node
    ports:
      - 100:3000
    volumes:
      - app_data:/app
    networks:
      - connect
  web:
    image: nginx
    ports:
      - 101:80
    networks:
      - connect
    volumes:
      - web_data:/usr/share/nginx/html
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_PORT=80    

networks:
  connect:
    driver: bridge

volumes:
  app_data:
    driver: local
  web_data:
    driver: local