version: "3.4"

services:
  web:
    image: nginx:alpine
    networks:
      - default
    ports:
      - "8080:80"  # Expose port 80 in the container on port 8080 on the host
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - default
    ports:
      - "5432:5432"  # Expose port 5432 for PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: webdb

# Define the network as a bridge for container communication
networks:
  default:
    driver: bridge

# Define a named volume for persistent database storage
volumes:
  db_data:
    driver: local
