version: "3.4"

services: 
    nginx:
        image: nginx:alpine
        ports: 
            - 100:80
        volumes:
         - /usr/share/docker/www:/www
    jenkins:
        image: jenkins/jenkins:lts-jdk17
        ports: 
            - 101:8080
        volumes:
         - /usr/share/docker/jenkins:/var/jenkins_home
