version: "3.4"

services: 
  nginx1:
    image: nginx
    ports: 
      - 81:80
    networks: 
      - nginx-network
  nginx2:
    image: nginx
    ports: 
      - 82:80
    networks: 
      - nginx-network

networks:
  nginx-network:
    driver: bridge